export const NATIVE_API = "nativeApi";
export const IPC_KEYS = {
    REQUEST_OPEN_DIR: "REQUEST_OPEN_DIR_IPC",
    CREATE_WEBM_RESPONSE: "CREATE_WEBM_IPC",
    REQUEST_OPEN_FILE_PLACE: "REQUEST_OPEN_FILE_PLACE_IPC",
} as const;